services:
  gift-certificates-db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env

volumes:
  db-data:
    driver: local
